### ISSUE TITLE
Usage Report

### ISSUE THREAD

**Issue by wahmedswl** [Unleash/unleash-client-dotnet#105]
**Describe the bug**
```Unleash.Client``` is not reporting Usage of the Toggle like JS sdk does. Is there some parameter or config that needs to be enabled for this feature?

![image](https://user-images.githubusercontent.com/15020561/183434113-d867815c-1557-4951-a2ee-cfbd26b9188a.png)

```iApartments_AccessHistoryFilters``` toggle is accessed via  ```Unleash.Client``` and all other via JS sdk. 

Thanks

**Comment by andreas-unleash** [comment]
Hi @wahmedswl , thanks for bringing this to our attention. Which client sdk are you using?

**Comment by andreas-unleash** [comment]
The .Net client should report metrics by default, though

**Comment by wahmedswl** [comment]
If these are only reported when ```SendMetricsInterval``` then summary says the following ...
```
//
// Summary:
//     Gets or sets the interval in which metriccs are sent to the server. When null,
//     no metrics is sent. Default: null
public TimeSpan? SendMetricsInterval { get; set; }
```

**Comment by andreas-unleash** [comment]
This has now been changed [(PR pending](https://github.com/Unleash/unleash-client-dotnet/pull/106)) to default to 60 s as per our documentation.  Thanks for reporting this @wahmedswl !

**Comment by sighphyre** [comment]
Sounds like this is done. I'm going to close this, @wahmedswl feel free to reopen if your problem is not solved
