### ISSUE TITLE
Random error when accessing the temporary file "The process cannot access the file"

### ISSUE THREAD

**Issue by Iltony** [Unleash/unleash-client-dotnet#107]
**Describe the bug**
**We are getting the error. The process cannot access the file '/tmp/unleash.toggles-default-instancetag-v2.2.0.json' because it is being used by another process.**

Sometimes we are getting the error mentioned above in production. 

This is part of the StackTrace
` at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode)
   at Unleash.Internal.FileSystem.FileOpenCreate(String path)
   at Unleash.Scheduling.FetchFeatureTogglesTask.ExecuteAsync(CancellationToken cancellationToken)
   at Unleash.ClientFactory.UnleashClientFactory.CreateClientAsync(UnleashSettings settings, Boolean synchronousInitialization, IStrategy[] strategies)`

**To Reproduce**

We cannot reproduce the issue exactly, the way that we reproduce a similar issue was: 

1 - Create a new **console** project in visual studio for **.Net Core 6** 
2- Add reference to 
            Unleash.Client     Version="2.2.0" and 
            Newtonsoft.Json Version="13.0.1" 

3- In the program.cs replace the content by the following block
```
using SampleFlagsAppRunnerUnleash;
int maxIterations = 2;
var tasks = new List<Task>();

for (int i = 0; i < maxIterations; i++)
{
	tasks.Add(UnleashFactory.CreateAsync());
}

await Task.WhenAll(tasks);

Console.WriteLine("completed...");
Console.ReadLine();
```

4- Create a new file and name it UnleashFactory.cs and replace the content for the following block 
```
using Unleash;
using Unleash.ClientFactory;
using Unleash.Strategies;

namespace SampleFlagsAppRunnerUnleash; 

public class UnleashFactory
{
	public static async Task<IUnleash> CreateAsync(params IStrategy[] strategies)
	{
		string unleashApiAddress = <PLACE_API_ADDRESS_CLIENT>;
		string unleashAppName = "default";
		string unleashEnvironment = "development";
		string unleashInstanceTag = "unleashtag";
		string apiClientValue = <PLACE_API_CLIENT>;
		int expiration = 5;

		IUnleash? result = null;

		try
		{
			var factory = new UnleashClientFactory();

			var settings = new UnleashSettings
			{
				AppName = unleashAppName,
				Environment = unleashEnvironment,
				UnleashApi = new Uri(unleashApiAddress),
				InstanceTag = unleashInstanceTag,
				FetchTogglesInterval = TimeSpan.FromMinutes(expiration),
				CustomHttpHeaders = new Dictionary<string, string> { { "Authorization", apiClientValue } }
			};

			if (strategies.Length != 0)
			{
				result =  await factory.CreateClientAsync(settings, synchronousInitialization: true, strategies);
			}

			result = await factory.CreateClientAsync(settings, true);
		}
		catch (Exception ex)
		{
			var info = new
			{
				AppName = unleashAppName,
				Environment = unleashEnvironment,
				UnleashApi = new Uri(unleashApiAddress),
				InstanceTag = unleashInstanceTag,
				FetchTogglesInterval = TimeSpan.FromMinutes(expiration)
			};

			Console.WriteLine($"An error ocurrs creating the unleash client '{info}', {ex.Message}");
		}

		return result;
	}
}

```
5- Run the application
6- The error must be seeing. 

Note, the temporary file does not have to exists. once you get the error. It is not showed again.
In that case you need to change the value of **unleashInstanceTag** in the class **UnleashFactory**  for unleash generate a new temporary file.

**Expected behavior**
The temporary file is created and able to be accessed by another process. Without throwing an exception.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
 - Visual Studio 2022 Professional 17.3.2

**Comment by sighphyre** [comment]
Hi Iltony, based off the error output that you've given, I'm not so sure this is a bug. It sounds like you've got multiple Unleash instances running on the same machine in different processes with the same instance tag and they're trying to read/write to the same file. Ideally the instance tag should be unique per running process, which should make this issue go away

**Comment by Iltony** [comment]
Hi, possibly this was the root cause, I have set all the dependencies as singleton. Closing the issue, thanks for answering
