### ISSUE TITLE
feat: Add support for specifying HttpClientHandler

### ISSUE THREAD

**Issue by christianfosli** [Unleash/unleash-client-dotnet#114]
**Is your feature request related to a problem? Please describe.**
Our unleash instance which API's access is hosted internally (i.e. unleash.myclient.local address).
We use https, but with an internal CA cert that is not signed by a well known root authority.

When running an API as a docker container locally we get TLS verification errors when unleash client tries to fetch the features.

**Describe the solution you'd like**
Add a settable property to `Unleash.DefaultHttpClientFactory`, e.g.
```cs
public HttpClientHandler HttpClientHandler { get; set; }
```

so that I could (conditionally) do something like this in my Startup / Program.cs:

```cs
unleashSettings.HttpClientFactory ??= new DefaultHttpClientFactory();
unleashSettings.HttpClientFactory.HttpClientHandler = new HttpClientHandler()
{
    ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator
};
```

and update `DefaultHttpClientFactory` `Create` method to use it when constructing the httpClient.
```patch
-               var client = new HttpClient
+               var client = HttpClientHandler == null ? new HttpClient : new HttpClient(HttpClientHandler)
                {
                    BaseAddress = unleashApiUri,
                    Timeout = Timeout
                };
```

**Describe alternatives you've considered**
I can work-around this by implementing my own `Unleash.IHttpClientFactory` and set `unleashSettings.HttpClientFactory` to that.
However I would like to not have to repeat the other logic in `Unleash.DefaultHttpClientFactory` (e.g. adding default request headers and setting timeouts).

I could also work around this by updating the Dockerfile for my API so it already trusts my client's internal CA certificate,
but I can't easily obtain the CA cert at build time without storing it together with my API's source code, which would be inconvenient.

**Additional context**

**Comment by daveleek** [comment]
You could inherit the `Unleash.DefaultHttpClientFactory` instead of the `Unleash.IHttpClientFactory`. There's a couple of extension points in that which could serve your purpose if you override the [ConfigureHttpClient()](https://github.com/Unleash/unleash-client-dotnet/blob/main/src/Unleash/DefaultHttpClientFactory.cs#L54) method

**Comment by christianfosli** [comment]
Thanks for the suggestion :smile:
I looked at that, but as far as I can tell the HttpClientHandler must be supplied to HttpClient's constructor and can't be added/edited after instantiation.

**Comment by daveleek** [comment]
Argh I spoke too soon. you are indeed correct, it's all coming back to me now 😬

**Comment by christianfosli** [comment]
I'm happy with the PR #119 solution for this :smile: Thanks!

Should leave the issue open until 2.4.0 stable release is out?

**Comment by daveleek** [comment]
Brilliant, good to hear @christianfosli ! 2.4.0 release just went out with the fix for this, so should be safe to close now at least. I'll close with a comment. Meant to mention this properly in this issue before it was closed anyways.

**Comment by daveleek** [comment]
Added a feature to address this with PR #119 in release 2.4.0.
Documentation: https://github.com/Unleash/unleash-client-dotnet#httpmessagehandlerscustom-httpclient-initialization
