### ISSUE TITLE
Update the C# language version

### ISSUE THREAD

**Issue by alexeyzimarev** [Unleash/unleash-client-dotnet#116]
As people get used to C# 10 and 11 new features, maybe it's a good idea to revamp the SDK code.

I can submit a PR to change the language version to C# 11, update the CI pipeline to build using .NET 7, and make the code shorter without changing any functionality. But, it will be a large PR as it will touch every single code file.

**Comment by ivarconr** [comment]
Hi @alexeyzimarev, thanks for reaching out, and a willingness to contribute. 

We have to be somewhat conservative on which language features we take advantage of, this goes for SDKs across all languages. The main reason is that a lot of users will have a somewhat hard time upgrading, for multiple reasons.  By rewriting the SDK to take advantage of new features we might force users to stay on older versions of Unleash, and we would rather avoid having to many versions to maintain, as the complexity grows when you think about all the languages we currently support. 

This does not mean we will never upgrade, just that I would like to see more data on what is actually being used before we jump on a task like this. 

Do anyone know of a good source of such information in the C# ecosystem?

**Comment by alexeyzimarev** [comment]
Using the latest SDK doesn't impact compilation for legacy SDKs, either .NET 5+ or legacy .NET Framework targets.

I maintain RestSharp, and it's built using .NET 7 SDK targeting .NET 4.7.1, .NET Standard 2.0, .NET 6 and 7.
