### ISSUE TITLE
Support SystemTextJson

### ISSUE THREAD

**Issue by alefcarlos** [Unleash/unleash-client-dotnet#122]
The SDK uses Newtonsoft by default, but what about SystemTextJson ?

Should SystemTextJson be the default? 

How can I implement IJsonSerializer based on `SystemTextJson`?

**Comment by daveleek** [comment]
>> Should SystemTextJson be the default?
AFAIK it's only available in more recent .NET Core versions (3.0 onwards?), and this SDK has to support a wide range of target versions. Could be doable with preprocessor directives though

>> How can I implement IJsonSerializer based on SystemTextJson?
I think it depends on which version of .NET you are running. In 6 and 7 there are Serialize and Deserialize overloads that take streams, so a shallow proxy on top could do. 5 and down have overloads that passes strings around, so for the serializer you could read the incoming stream into a string and pass that along, and for the deserializer take the string received and put it in a memorystream that you return perhaps?

**Comment by alefcarlos** [comment]
@daveleek, I get it. What confused me was this part of the documentation:

```
The server api needs camel cased json, but not for certain dictionary keys. CamelCaseExceptDictionaryKeysResolver 
```

But the implementation doesnt need that, right?

I'm using .NET6.0, so will implement that and post here! Thank you for the response.
