### ISSUE TITLE
 Handling incorrect UnleashClient configuration

### ISSUE THREAD

**Issue by xiaoyangwang-geotab** [Unleash/unleash-client-dotnet#132]
Hello Unleash client .NET team,

I have a question about how to handle incorrect UnleashClient configuration. Specifically, I would like to know how to detect if the API token is incorrect or if the Unleash client is incorrectly configured when creating a client instance using UnleashClientFactory.CreateClient/CreateClientAsync.

Currently, we observe that an incorrect token results in an empty feature toggles collection without any exception being thrown. Do you have any suggestions on how to handle this, such as having an exception thrown, or is there a property from the UnleashClient instance that we can check to determine if the connection has been successfully established?

Thank you for your help!

**Comment by daveleek** [comment]
Hello @xiaoyangwang-geotab!

Have you found a solution to your question yet?
There should be an error thrown if the http request to fetch toggles fails. Incorrect token - is that a token-code that does not exist/or a typo? Or do you mean an existing token, but wrong type of token/token that doesn't have access to the configured project?

David

**Comment by xiaoyangwang-geotab** [comment]
Hi @daveleek 

Thank you for your response. Unfortunately, I have not been able to find a solution to the issue at this time.

I have attempted to use a non-existent token, as well as an admin token in the client, but neither of them resulted in the expected exception being thrown. Here is the section of code where I initialize my Unleash instance:
`        var settings = new UnleashSettings()
        {
            AppName = appName,
            UnleashApi = new Uri(apiUri),
            CustomHttpHeaders = new Dictionary<string, string>(StringComparer.InvariantCulture)
            {
                { "Authorization", apiToken } // The apiToken should only be the client token specified for production or development. Neither admin tokens nor personal access tokens will work.
            },
        };
        var unleashFactory = new UnleashClientFactory();
        var unleash = unleashFactory.CreateClient(settings, synchronousInitialization: true);
`

By the way, I am currently running the code on a local server. Not sure if there're differences between the behavior of the code on a production server and a local server regarding this issue.

Thanks!

**Comment by daveleek** [comment]
Thank you @xiaoyangwang-geotab, prod vs local shouldn't behave differently in that regard!
Thanks for the code snippet, I'll have a look!

**Comment by daveleek** [comment]
Hey @xiaoyangwang-geotab. So it turns out if you set log level to Verbose then error messages should appear in the log. We're looking into it for a future improvement, but the knowledge should at least enable you to see error messages from API calls.

**Comment by xiaoyangwang-geotab** [comment]
Thanks @daveleek So how to set the log level to Verbose? Additionally, if an error is logged, I can review the log within the code to identify any failures. Is that what you meant?

**Comment by daveleek** [comment]
Hi @xiaoyangwang-geotab
> So how to set the log level to Verbose?

that depends on your logging framework of choice. in my repro I used `Serilog` and the console sink:

```
    using var log = new LoggerConfiguration()
    .MinimumLevel.Verbose() // Setting to Verbose here
    .WriteTo.Console()
    .CreateLogger();
```

> Additionally, if an error is logged, I can review the log within the code to identify any failures. Is that what you meant?

Setting log level to Verbose should make the error messages appear in the log output of your application. It will not raise exceptions that stops execution though, it runs in a background timer/thread

**Comment by sighphyre** [comment]
Hey @xiaoyangwang-geotab, I realise I'm super late to this thread, apologies. 

Just want to unpack this one a little, so the philosophy of the Unleash SDKs is that they should be tolerant to failure and not impact their hosting application in the case of errors. To this end, the behaviour here is that the SDKs shouldn't need to be able to sync to Unleash to work correctly, it should have a backup file saved from the last time they synced to Unleash and they should sync as soon as it's able to reach Unleash. This is important here because if an API key is revoked in the Unleash UI, the SDK should be able to continue to work against its backup file.

I realise this isn't your problem, I'm just trying to provide some context on why the SDK works the way it does. That being said, I'm not sure I correctly understand the problem here, is there a reason why you can't set the token correctly here? What are you actually trying to solve?

We're more than open to trying to resolve the issue but I'm not 100% confident yet that bubbling the underlying exception is the correct behaviour here.

**Comment by xiaoyangwang-geotab** [comment]
Hi @sighphyre, thank you for explaining the concept of tolerance to failure. I do understand the design, and It worked well while I was testing it. 

However, I have a concern regarding the initialization of the unleash instance. In the event that someone enters the wrong API token in the config (which could happen in reality), how can we determine if the unleash configuration is incorrect? Even if everything is configured correctly and the unleash instance is created successfully, how can we know if the unleash server is down? We may not necessarily encounter an exception, but we would like to have a property or some indicator that indicates when something is going wrong. 

Generally, I think our concern is that we want to be notified of any failures directly from the unleash instance instead of having to rely on logs. 

Thanks!

**Comment by daveleek** [comment]
> 1. Incorrect configuration ... Is it possible to correct the configuration and apply the changes without restarting our application?

Once the settings have been added to the Unleash SDK instance they're handed over to the internal services needing them, and are hard to replace on the instance itself.

Unleash is typically (and we really recommend this) configured as a singleton, so you'd have to dispose the whole instance of it first and then start up a new one, and if you're using Dependency Injection you'd need to find a way to replace the singleton in the container.

> 2. Unleash server is down during initialization: In this situation, an exception would be thrown. Is there a retry policy implemented for such cases?

If Unleash is initialized with `synchronousInitialization: true`, then no. It will crash and there's no retries.
If Unleash is initialized with `synchronousInitialization: false` then yes, Unleash will log exceptions but will retry on interval as configured (FetchTogglesInterval) and will recover once Unleash instance comes online.

**Comment by xiaoyangwang-geotab** [comment]
Thanks @daveleek 

I have a couple more questions that extend from the second question I asked earlier:

1. If Unleash is initialized with `synchronousInitialization: false`, would we also be able to determine if the server is down from the error callback?
2. In the event of a server outage during initialization, would the Unleash instance still read feature toggles from backup files generated during the last successful initialization or fetching?
We attempted to save the backup files outside of the container and use them when the Unleash instance is initialized with empty toggles (which would have the error callback indicates an issue in your future implementation). However, the problem we encountered is that each initialization creates a new backup file, making it difficult to manage. This is likely why the default backup file location is the temporary folder. Is there a more effective approach to handle this situation?

Thank you very much for your help.

**Comment by daveleek** [comment]
Hi @xiaoyangwang-geotab!

> 1. If Unleash is initialized with synchronousInitialization: false, would we also be able to determine if the server is down from the error callback?

Yes. We are adding information to the event in the callback that should enable you to determine if the server is down, up, or returning odd statuses.

> 2. In the event of a server outage during initialization, would the Unleash instance still read feature toggles from backup files generated during the last successful initialization or fetching? ` ... ` Is there a more effective approach to handle this situation?

Yeah I had a look at this to understand why it would be doing this - the backup file should always be restorable. Have you set the `InstanceTag` property on the `UnleashSettings` when you're initializing Unleash? If not then this property is set to a random value, this value is also added to the backup file name. If you set the `InstanceTag` then the file name will be consistent across restarts and should work with backup files being mounted back in.

Another option is to look at [bootstrapping unleash](https://github.com/Unleash/unleash-client-dotnet#bootstrapping)

**Comment by daveleek** [comment]
We have now released the `2.4.4` update which brings the option of registering a callback to be notified of errors occurring in the Unleash SDK. It has been added to [the event handling registration callback](https://github.com/Unleash/unleash-client-dotnet/tree/2.4.4#handling-events)

**Comment by xiaoyangwang-geotab** [comment]
Hi @daveleek, thank you for your InstanceTag suggestion and the 2.5.0 release from your team. We have implemented both of them, and they are working flawlessly now. 
We appreciate your support and the efficiency with which your team addressed our needs. 

Take care,
Xiaoyang

**Comment by sighphyre** [comment]
Thanks for the feedback @xiaoyangwang-geotab!

**Comment by daveleek** [comment]
Good to hear, thank you @xiaoyangwang-geotab!
