### ISSUE TITLE
Don't use string interpolation for log messages

### ISSUE THREAD

**Issue by lukos** [Unleash/unleash-client-dotnet#133]
**Describe the bug**
This is a bug in the least serious sense (and I might be wrong) but you shouldn't be using string interpolation to create message templates when you log errors etc. Explanation is here: https://nblumhardt.com/2015/01/c-6-string-interpolation-and-serilog/ but consider the existing code example:

`Logger.ErrorException($"UNLEASH: Unhandled exception from background task '{name}'.", ex);`

or a worse example:

`Logger.Trace($"UNLEASH: Error {response.StatusCode} from request '{resourceUri}' in '{nameof(UnleashApiClient)}': " + error);`

This will create a message template with the values of the interpolated parameters embedded in it as opposed to passing it as a parameters:

`Logger.ErrorException("UNLEASH: Unhandled exception from background task '{TaskName}'.", ex, name);`

Why is this an issue? In many logging tools, having the same messaging template but with different placeholders allows the logging system to spot a proliferation of the same error even with different parameters, for example lots of Unhandled errors from different background tasks, whereas if you have hard-coded the template, it just looks like lots of completely different log messages.

Lots of logging frameworks also support filtering on the parameters so in the example above, if done properly, you could search for e.g. "report-metrics-task" because it is passed as a separate parameter. By creating the template in-advance with the parameters, your only possibility would be a full-text search which would be either really slow or might pick up lots of results you are not interested with.

There are plenty of articles about doing it with the format string instead of interpolation.

**Comment by daveleek** [comment]
Thank you for bringing this up @lukos, you are of course absolutely correct that this could be handled way better!
There are other things we'd like improve with the logging code as well, the complexity is one of them.

It's not going to happen right now, but we are in the process of looking at this and some alternatives to how we manage/maintain/keep this SDK up to date, as well as other SDKs.

You are of course welcome to submit a pull request, we'd be happy to look at it

**Comment by daniel-richter** [comment]
> There are plenty of articles about doing it with the format string instead of interpolation.

FYI: It would be possible to use message templated _and_ string interpolation - see  https://github.com/serilog/serilog/issues/1643#issuecomment-1118085771
