### ISSUE TITLE
Unhandled exception when writing to toggle file during startup

### ISSUE THREAD

**Issue by SMLVE** [Unleash/unleash-client-dotnet#136]
**Describe the bug**
Using the UnleashClientFactory to create an unleash client on startup, we sometimes get an unhandled exception when writing to the toggle file. This does not happen very often. But every time it does, the startup time of our application, according to Cloud Run's monitoring tool, is very long (over 30 seconds). 

Here is how Unleash is set up 
```
public static class UnleashExtension
{
    public static IServiceCollection AddUnleash(this IServiceCollection services, IConfiguration config)
    {
        var settings = new UnleashSettings() { SendMetricsInterval = null };
        config.GetSection("Unleash").Bind(settings);

        var unleashFactory = new UnleashClientFactory();
        var unleash = unleashFactory.CreateClient(settings);

        services.AddSingleton(unleash);
        return services;
    }
}
```

Here is the stack trace. 
```
UNLEASH: Unhandled exception when writing to toggle file '/tmp/unleash.toggles-UEAT-localhost-generated-192738-unleash-client-dotnet:v2.4.3.json'.
System.IO.IOException: The process cannot access the file '/tmp/unleash.toggles-UEAT-localhost-generated-192738-unleash-client-dotnet:v2.4.3.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode)
   at Unleash.Scheduling.FetchFeatureTogglesTask.ExecuteAsync(CancellationToken cancellationToken)
```

**To Reproduce**
Only happens once in a while. Unable to reproduce locally. 

**Expected behavior**
The unleash client shouldn't try and access the same file at the same with a different process. 

**Additional context**
The application is running on Cloud Run within a docker container.
DOTNET VERSION=7.0
Unleash client version = 2.4.3 (latest)

**Comment by daveleek** [comment]
Thank you for bringing this up @SMLVE. If you don't mind, what's your polling interval set to (if not default)?

**Comment by SMLVE** [comment]
It's set to 30 seconds, which is the default I think.

**Comment by SMLVE** [comment]
Thanks, for the detailed explanation and for getting back to us so quickly. We are going to update our package whenever the fix is released!

**Comment by EricStG** [comment]
@daveleek FYI, this happens in a Docker with no volumes mounted. There's only 1 process in that container, and that's the ASP.NET Core app using Unleash.

**Comment by daveleek** [comment]
FYI: Closing as we released an improvement on randomization of instance tags in v [3.0.0](https://github.com/Unleash/unleash-client-dotnet/releases/tag/3.0.0)
