### ISSUE TITLE
Counting variants in the `ToggleCount` is incorrectly implemented

### ISSUE THREAD

**Issue by nhathongly** [Unleash/unleash-client-dotnet#138]
The following line of code in the `ToggleCount` class won't increase the variant counts in the `ConcurrentDictionary` because `Interlocked.Increment()` cannot be applied to properties.

https://github.com/Unleash/unleash-client-dotnet/blob/b5437c2c15e0eedfec788fe4273c16fc67b0e432/src/Unleash/Metrics/ToggleCount.cs#L31

There are some possible fixes, such as:

```csharp
// Using  StrongBox
 private ConcurrentDictionary<string, StrongBox<long>> variants = new ConcurrentDictionary<string, StrongBox<long>>();

Interlocked.Increment(ref variants[variantName].Value);
```

or

```csharp
// Using ConcurrentDictionary.AddOrUpdate
variants.AddOrUpdate(variantName, 1, (k, v) => Interlocked.Increment(ref v));
```

**Comment by daveleek** [comment]
Thank you for reporting this @nhathongly, we'll have a look!

**Comment by nhathongly** [comment]
Do you have any updates on this? I wish it would get resolved to view the variant metrics in the Unleash Admin.

**Comment by thomasheartman** [comment]
@nhathongly Hey! No updates yet, but you caught me just as I was about to start looking into it, so expect more to come soon 😄  Thanks for reporting it and for the suggestions.
