### ISSUE TITLE
Null ref in ToggleBootstrapFileProvider, FileSystem is null.

### ISSUE THREAD

**Issue by TomKnowlesPlayside** [Unleash/unleash-client-dotnet#141]
**Describe the bug**
Filesystem is internal so it cannot be created manually, and is not initialised until the Services are constructed. This means there is no way to create a ToggleBootstrapFileProvider in the UnleashSettings, and UseBootstrapFileProvider does not work because FileSystem is null. This means you cannot use the ToggleBootstrapFileProvider to generate the initial cache.

**To Reproduce**
1. Create an unleash settings, configure as normal.
2. Call UnleashSettings.UseBootstrapFileProvider
3. Create the unleash client
4. Null reference exception on ToggleBootstrapFileProvider.Read, line 32.

**Expected behavior**
Toggles should be loaded from the supplied files

**Screenshots**
![image](https://github.com/Unleash/unleash-client-dotnet/assets/135289605/52572f19-59e1-45b8-8ce9-3883065b6d53)

**Additional context**
I'm using this sdk in Unity engine to connect to GitLab feature flags, which use unleash. I need to read from a local backup since devices aren't guaranteed to have internet access, and versions might be out of date, so we're taking a snapshot of all the feature flags and saving them in our ci pipeline.

I'm currently working around that problem by duplicating the ToggleBootstrapFileProvider, and using System.File to read without the IFileSystem.

**Comment by daveleek** [comment]
Thank you @TomKnowlesPlayside! We'll have a look!

**Comment by TomKnowlesPlayside** [comment]
Thank you, I appreciate it
