### ISSUE TITLE
Gradual rollout without context always fails

### ISSUE THREAD

**Issue by thomasheartman** [Unleash/unleash-client-dotnet#144]
**Describe the bug**

If you use a gradual rollout strategy and call `IsEnabled` or `GetVariant`, you'll always get `false` or the disabled variant, *even if the rollout percentage is 100%*.

This appears to be because of how the SDK requires the context to do stickiness/rollout calculation. 
This should be in line with how other SDKs treat this.

**To Reproduce**
1. Go to Unleash; add a feature with a gradual rollout of 100%.
2. Use the SDK to check whether it's enabled. 
3. With context: observe that it's enabled. Without context, observe that it is *not* enabled.

**Expected behavior**

A gradual rollout of 100% should expose  a feature to all users. 

Granted, there is some ambiguity when you don't provide a context and the rollout is betweeen 0.1% and 99.9%, but at that point, I'd expect it to be random based on the chance of exposing it. However, this should be handled the same way as with other SDKs.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: (Browser version? 114)

**Additional context**
This has been a recurring questions from the community, so there's many people who find this behavior confusing.

**Comment by daveleek** [comment]
We should be able to close this now that we've shipped #151

**Comment by thomasheartman** [comment]
Nice one 😄
