### ISSUE TITLE
Support for AOT compiled runtime

### ISSUE THREAD

**Issue by TomKnowlesPlayside** [Unleash/unleash-client-dotnet#148]
**Is your feature request related to a problem? Please describe.**
I am trying to run unleash through an AOT compiled IL2CPP runtime. However the LibLog library uses dynamics, which are not supported.

**Describe the solution you'd like**
A way to disable logging, a way to implement my own logger which works in IL2CPP without needing to fork and manage my own version of the software, or a new logging system.

**Describe alternatives you've considered**
LibLog has been deprecated since 2019, and the author recommends switching to use https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions.

**Additional context**
The exception thrown.
![image](https://github.com/Unleash/unleash-client-dotnet/assets/135289605/5b3c0333-b3d6-4a79-9cc7-d968e95bf638)

This is the internal exception.
![image](https://github.com/Unleash/unleash-client-dotnet/assets/135289605/6ffe146b-19d9-4880-8d5d-e8e1fb33dbd8)

**Comment by daveleek** [comment]
Thank you @TomKnowlesPlayside!
Yeah the logging is on our radar, we're planning to address it in the not too distant future!

**Comment by TomKnowlesPlayside** [comment]
Hey David, thanks for looking into this! Ended up forking. Just for reference, besides rewriting the logging, I also needed to remove the dynamic json serializer, and change the SafeTimerChange function in UnleashExtensions to use overrides instead of dynamics.

**Comment by sighphyre** [comment]
Hey @TomKnowlesPlayside, this is something we really want to do but priorities are taking us elsewhere at the moment. I'm going to close this right now, but when we do this, we'll communicate the changes out over the patch notes

**Comment by JacobMillward** [comment]
Just ran into this problem again in 2025, would love to see this sorted.
