### ISSUE TITLE
System.Text.Json.JsonException when dezerializing json to Unleash.Internal.ToggleCollection

### ISSUE THREAD

**Issue by erandjo** [Unleash/unleash-client-dotnet#173]
**Describe the bug**
The id in Segment is defined as a string but unleash seems to return a json number. This causes a System.Text.Json.JsonException: The JSON value could not be converted to Unleash.Internal.Segment when using System.Text.Json for dezerialization. The bug is not noticable when using Newtonsoft.

unleash-client-dotnet version: 4.0.0

Segment.cs: https://github.com/Unleash/unleash-client-dotnet/blob/cccf3efe3cb2effd5580834efc864b1f0542160e/src/Unleash/Internal/Segment.cs
```
﻿using System;
using System.Collections.Generic;
using System.Text;

namespace Unleash.Internal
{
    public class Segment
    {
        public string Id { get; }
        public List<Constraint> Constraints { get; }
        public Segment(string id, List<Constraint> constraints = null)
        {
            Id = id;
            Constraints = constraints ?? new List<Constraint>();
        }
    }
}

```
**To Reproduce**
1. Create a simple app that reference "unleash.client" Version="4.0.0".
2. Add  JsonSerializer = new TextJsonSerializer() to UnleashSettings.
3. Wrap System.Text.Json serializer:

```
internal class TextJsonSerializer : IJsonSerializer
{

    T IJsonSerializer.Deserialize<T>(Stream stream)
    {
        var options = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        };
        var instance = JsonSerializer.Deserialize<T>(stream, options);
        if (instance == null)
        {
            throw new Exception("The result of serializing feature toggle is null");
        }

        return instance;
    }


    void IJsonSerializer.Serialize<T>(Stream stream, T instance)
    {
        JsonSerializer.Serialize<T>(stream, instance);
    }
}
```
4. Fetch feature toggles from unleash
5. See the error when dezerializing.

**Expected behavior**
instance should be Unleash.Internal.ToggleCollection after dezerialization.

**Suggested fix**
Change type of id in Segment.cs to int.

**Comment by daveleek** [comment]
Thank you for raising this @erandjo! We'll take a look

**Comment by daveleek** [comment]
Hey @erandjo - this issue was auto-closed when we closed the PR. We've fixed the issue and will publish a new version sometime within the next week!

**Comment by erandjo** [comment]
That sounds good! I am closing the issue.
