### ISSUE TITLE
Load/use feature flags with IConfiguration

### ISSUE THREAD

**Issue by thompson-tomo** [Unleash/unleash-client-dotnet#184]
**Summary of pain point**
I wish for unleash to hook into IConfiguration to enable offline feature management & alternative syncing of rules. This is avoid having to implement a local api for software to call which is a no-op. Note I already have a secured solution to sync the feature flags to local servers and don't want local solution to talk directly to unleash.

**The solution I'd like**
unleash client for dotnet includes the following:
- A dotnet configuration provider for fetching feature flags from unleash including configurable refresh interval
- unleash uses feature flag properties as defined in IConfiguration.

**Describe alternatives you've considered**
Rolling out my own api which behaves like unleash

**Comment by daveleek** [comment]
Answered in #183

**Comment by daveleek** [comment]
This is not going to get addressed in the SDK. As discussed in #183, the SDK already supports Bootstrapping and backup file loading on startup
