### ISSUE TITLE
Have Strategies also Implement Microsoft Feature management

### ISSUE THREAD

**Issue by thompson-tomo** [Unleash/unleash-client-dotnet#185]
**Summary of pain point**
I wish to be able to use unleash strategies with Microsoft Feature management library.

**The solution I'd like**
To be able to use microft Feature management library but have support for all unleash supported strategies
- All of the unleash policies are available as implementations of IFeatureFilter in Microsoft SDK

**Describe alternatives you've considered**
Making my own implementatiom of the strategies and only do the ones I need

**Comment by daveleek** [comment]
Answered in #183

**Comment by daveleek** [comment]
This has been answered in #183 with suggestions on how this could be approached in users app. This is not going to be addressed in the SDK
