### ISSUE TITLE
Record metrics using System.Diagnostics.Metrics

### ISSUE THREAD

**Issue by thompson-tomo** [Unleash/unleash-client-dotnet#191]
**Is your feature request related to a problem? Please describe.**
I would like to have all of application metrics available in one central location (elk)

**Describe the solution you'd like**
The current metric collection processed is replaced with metrics being collected in a consistent manner to other libraries. The metric exporter is an opt-in service

**Describe alternatives you've considered**
Scraping metrics from unleash to present in ELK

**Comment by daveleek** [comment]
This is not going to get addressed. Suggest looking into [admin api metrics](https://docs.getunleash.io/reference/api/legacy/unleash/admin/metrics) in Unleash
