### ISSUE TITLE
Split of nuget package

### ISSUE THREAD

**Issue by thompson-tomo** [Unleash/unleash-client-dotnet#192]
**Is your feature request related to a problem? Please describe.**
As the library is modernised/integrated it should be possible for use to drop in only the parts they want of unleash

**Describe the solution you'd like**
I would like to have the nuget split so that I only add what I need. Proposal would be
- Unleash = current functionality + dependencies of all below packages
- Unleash.Abstractions = generic models/Interfaces to be shared/Implemented. Is dependency for all other packaged
- Unleash.Configuration = fetches toggles From unleash and loads them into IConfiguration
- Unleash.FeatureManagement = a library which allows for registering library with DI etc
- Unleash.MetricsExporter = exports All metrics prefixed with Unleash to Unleash
- Unleash.Strategies = implementation of the supported strategies including the Microsoft wrappers

**Comment by daveleek** [comment]
Answered in #183. We're considering a future improvement with the setup/app-hosting part of the SDK with potentially additional packages for platform support (.NET Framework, .NET Core)

**Comment by daveleek** [comment]
This is not going to be addressed. We will however look at improving hosting options/setup for .NET Core/5/6/7/8 etc and .NET Framework <= 4.8 in the future, but that discussion is ongoing
