### ISSUE TITLE
Negate operator not work in dot net sdk 

### ISSUE THREAD

**Issue by mohsen-khalili** [Unleash/unleash-client-dotnet#195]
**Describe the bug**
in segment if you add Constraints and use negate operator its not work in dot net sdk and return false result

**To Reproduce**
1. Go to create segments
2. Add 'dummy name'
3. Click on Next
4. Select context 'UserId'

**Screenshots**
negate off:
![Screenshot 2024-01-07 at 09 43 52](https://github.com/Unleash/unleash-client-dotnet/assets/7185516/79607c9e-7b6f-4294-a913-5159bb5a0ff5)
negate on:
![Screenshot 2024-01-07 at 09 51 09](https://github.com/Unleash/unleash-client-dotnet/assets/7185516/0d9760a7-cdfc-407f-b975-ad2ded8e9117)

**Comment by mjalil** [comment]
This also requires some additional tests in the `client-specification` project at [specifications/09-strategy-constraints.json](https://github.com/Unleash/client-specification/blob/main/specifications/09-strategy-constraints.json)

**Comment by daveleek** [comment]
Thank you for raising this @mohsen-khalili! We'll take a look at it!

**Comment by sjaanus** [comment]
Fix released in [4.1.3](https://github.com/Unleash/unleash-client-dotnet/releases/tag/4.1.3)
