### ISSUE TITLE
Removal of Microsoft.CSharp package dependency

### ISSUE THREAD

**Issue by thompson-tomo** [Unleash/unleash-client-dotnet#201]
**Describe the solution you'd like**
I would like for the Microsoft.CSharp package to be removed as a dependency as it appears to not be used and as such is just bloating the dependencies

**Describe alternatives you've considered**
Implementing more target frameworks but if not needed for net standard 2.0 we don't gain by adding a framework rather than simply cleaning the package

**Additional context**
Appears to have been introduced with pull request #7 in 1.3.4

**Comment by sighphyre** [comment]
Hey @thompson-tomo,

We'd like to do this but I'm not sure we can right now (easily at least). This is required for older versions of .NET to make `dynamic` work. At the moment, we only seem to target .net standard, which would still need this I believe.

We probably can and should rework the build in this project to bring it up to date but that's probably a bigger task than just this. So in the short term I'm open to suggestions that don't break this project for folks using older versions of .NET

**Comment by thompson-tomo** [comment]
Hi @sighphyre before i logged this issue, i had taken a look and it for some reason was able to compile without that dependency however when i retested this morning, that wasn't the case. So must of been a cache issue or something. However what i have found is that if we add a netcoreapp 3.1 target this dependency is no longer needed. Hence see PR for additional framework which externalize this dependency. :)

**Comment by thompson-tomo** [comment]
Pr is pending. Re-open
