### ISSUE TITLE
synchronousInitialization: true should throw exception if exception happens in the init flow (network, authorization, etc)

### ISSUE THREAD

**Issue by Meister1977** [Unleash/unleash-client-dotnet#210]
[2-2009](https://linear.app/unleash/issue/2-2009/net-sdk-unhandled-background-exceptions)

Tracking on EG board

Needs comms from SR. @david  to shout when there's needs

**Comment by daveleek** [comment]
Thank you for the bug report @Meister1977! We'll have a look!

**Comment by daveleek** [comment]
Hello @Meister1977. We have a fix for this on the way out!

**Comment by daveleek** [comment]
Hello @Meister1977. We've just released 4.1.8 which should address this issue!
