### ISSUE TITLE
Built-in JSON serialization without reflection

### ISSUE THREAD

**Issue by gastonfournier** [Unleash/unleash-client-dotnet#221]
**Is your feature request related to a problem? Please describe.**
Depending on a [Json serialization](https://github.com/Unleash/unleash-client-dotnet?tab=readme-ov-file#json-serialization) library that requires a custom implementation, can lead to errors. In particular, when defining a custom serialization with system.text if we forget to do `stream.Position = 0;` the payload will not be serialized properly, leading to errors downstream.

**Describe the solution you'd like**
Serialization should be provided by the SDK, it's not something users should override, as there's only 1 correct way of serializing the payload. The downside is that the actual users, that are using a custom serializer might cause a crash at runtime.

**Describe alternatives you've considered**
None, but open to suggestions

**Additional context**
As a sample test, I wrote a test for System.text as serializer. It's currently not working because the test compares strings to strings and the only difference is the sort order of fields. So it's the test that needs to change. On top of that, the test is not covering serialization of metrics, so it's incomplete. But it's a good enough to prove the point that serialization is dangerous if left in the hands of users and it should be handled by the SDK without giving users the ability to override it:

https://github.com/Unleash/unleash-client-dotnet/compare/system-text-serialization-test?expand=1

**Comment by gastonfournier** [comment]
We're making this issue visible after some issues caused by custom serializers, but it's not gonna be prioritized soon. We'd like to collect some feedback from the community (you), and why not some contribution.

**Comment by PhbsSmn** [comment]
Why not opting for System.Text.Json rather than still using the Newtonsoft implementation?
Did not glance too deeply in the code base but for the things I needed it wasn't such a hard thing, and by doing so you could tap into the power of source generated serialization as well for the newer .NET versions.

Not sure how backwards compatible this is though since it's been a long time now that I used .NET framework.

**Comment by sighphyre** [comment]
> Why not opting for System.Text.Json rather than still using the Newtonsoft implementation? Did not glance too deeply in the code base but for the things I needed it wasn't such a hard thing, and by doing so you could tap into the power of source generated serialization as well for the newer .NET versions.
> 
> Not sure how backwards compatible this is though since it's been a long time now that I used .NET framework.

Yeah I think this makes sense

**Comment by sighphyre** [comment]
Handled by #249

**Comment by sighphyre** [comment]
This should be out in the next major release
