### ISSUE TITLE
Support for hostname strategy

### ISSUE THREAD

**Issue by evozniak** [Unleash/unleash-client-dotnet#223]
**Is your feature request related to a problem? Please describe.**
In the Unleash-client 2.2.0 I could use the IPs strategy for hostnames, but in the latest client there is a validation for allowing only IP addresses (IPAddress.TryParse) in [RemoteAddressStrategy.cs](https://github.com/Unleash/unleash-client-dotnet/blob/93f4d88a1058581960752d754954dee665a16435/src/Unleash/Strategies/RemoteAddressStrategy.cs#L23)

**Describe the solution you'd like**
The Activation Strategies page in the documentation already shows how to use [hostnames](https://docs.getunleash.io/reference/activation-strategies#hostnames) but apparently, the context of this client doesn't support the property `applicationHostname` like the documentation shows, only the property `remoteAddress` is available, but that is for the IPs strategy.

**Additional context**
Is there a guide on using Hostnames or is it not supported yet?

**Comment by evozniak** [comment]
I looked at the unit tests, and, the only way of using hosts is via Environment variables.
`Environment.SetEnvironmentVariable("hostname", "myhost");`

Is there a plan to support `applicationHostname` property? I need to dynamically adjust the hostname depending on the subdomain.

**Comment by chriswk** [comment]
Hi @evozniak , sorry for the late answer, this was assigned to a colleague of mine and then he unfortunately went on vacation.

Trying to avoid confusions, and really working from my Java SDK expertise.

The client resolves it's hostname (or tries to).
```csharp
       public ApplicationHostnameStrategy()
        {
            hostname = Environment.GetEnvironmentVariable("hostname") ?? Dns.GetHostName();
        }
```
Then to see if the strategy should evaluate to true it looks at the parameter called "hostNames", lowercases each name in the list, lowercases the hostname that was found and checks to see if any of them are equal

```csharp
if (parameters.TryGetValue(HostNamesParam, out var hostnames))
            {
                if (hostnames == null || hostnames == string.Empty)
                    return false;

                return hostnames
                    .ToLowerInvariant()
                    .Split(',')
                    .Select(x => x.Trim())
                    .Contains(hostname.ToLowerInvariant());
            }
```

The string `applicationHostname` is just the identifier for this kind of strategy, all our SDKs use this to identify how to evaluate the toggle based on which strategy.

**Comment by daveleek** [comment]
@evozniak thank you for reaching out, looks like this has been answered so I will close this issue. If you have further questions feel free to reopen or create a new issue!
