### ISSUE TITLE
Default config should not create files and Unit Tests should not create files

### ISSUE THREAD

**Issue by DevinCrumb** [Unleash/unleash-client-dotnet#234]
**Describe the bug**
The Unleash Client is creating unwanted and prosibly problimatic files. The application may not have permission to write to the directory used by the client or there may be other reasons where creating a file is problematic. Default should be to not use the file system.

Also, when running the Unit Test, it should not be creating files or only create files in a build specific directory that it cleans up.  The issue with the way it is doing things now, there could be conflict if the Unit Test is run twice at the same time with the same temp directory and it fills up the file system with the files it leaves behind after the tests are run.

**Expected behavior**
No files created unless explicitly configured and no file remain after running Unit Tests.

**Comment by ivarconr** [comment]
Hi thanks for your issue. 

> The Unleash Client is creating unwanted and prosibly problimatic files. The application may not have permission to write to the directory used by the client or there may be other reasons where creating a file is problematic. Default should be to not use the file system.

Unleash will by default use the system defined tmp folder. This can be configured by the user to be a different folder via the "LocalStorageFolder".  Currently there are no option to disable this feature in the dotnet SDK, but it makes sense to add it as an optional feature in a future release. 

> Also, when running the Unit Test, it should not be creating files or only create files in a build specific directory that it cleans up. The issue with the way it is doing things now, there could be conflict if the Unit Test is run twice at the same time with the same temp directory and it fills up the file system with the files it leaves behind after the tests are run.

Is this an actual issue you discovered or something you believe can be a problematic thing in the future? Given that the SDK is supposed to generate back-up files as part of the normal operation, its important that this functionality is also tested. The Unit test can control both the folder being used and the actual name of the file being used for the test. I am not aware that this has caused any issues for any of the contributors on this SDK over the years we have maintained the SDK. In general I agree that most Unit tests should use a in-memory backup mechanism when that feature is added to this SDK (as suggested above) and only have a focused unit test validating the backup file integration.

**Comment by daveleek** [comment]
@DevinCrumb thank you for reaching out. Looks like the question has been answered, further work like @ivarconr mentioned is on the radar for future improvements. I'll close this issue, but if you have more questions feel free to reopen or create a new issue!
