### ISSUE TITLE
The unleash package is not using a reserved prefix

### ISSUE THREAD

**Issue by PhbsSmn** [Unleash/unleash-client-dotnet#243]
**Is your feature request related to a problem? Please describe.**
Currently anyone in the world could create an unleash nuget package since the prefix is not reserved on nuget.org. This makes it harder to fully trust the library in an automated way.

**Describe the solution you'd like**
Register the unleash prefix via nuget.org, its super easy and free of charge. I did it once for setting up a session about dependency chain attacks.
https://learn.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#id-prefix-reservation-criteria

**Describe alternatives you've considered**
There are no really alternatives. The longer you wait as a service provider and get a larger user base the more appealing you will become for someone with bad intentions.

**Comment by daveleek** [comment]
Thank you for raising this @PhbsSmn, we'll take a look at it!

**Comment by PhbsSmn** [comment]
You’re welcome

**Comment by daveleek** [comment]
Hello @PhbsSmn, we've now received confirmation from the NuGet account team that the prefix Unleash has been reserved for our organization, and we've verified that we have gotten the reservation mark on our two packages.

Thank you again for bringing this to our attention
