### ISSUE TITLE
currentTime strategy constraint doesn't work

### ISSUE THREAD

**Issue by tlevesque-ueat** [Unleash/unleash-client-dotnet#245]
**Describe the bug**
If I create a strategy with a `DATE_AFTER` constraint on `currentTime`, with a date in the past, the feature flag is always considered disabled.
The same feature flag works fine on the frontend with [unleash-proxy-client-js](https://github.com/unleash/unleash-proxy-client-js).

**To Reproduce**
1. Create a feature flag with a gradual rollout strategy with 100% rollout
2. Add a constraint on `currentTime` with `DATE_AFTER` and a date in the past
3. In the app, call `IUnleash.IsEnabled("MyFeatureFlag")`
4. It always returns false, whether the current date is before or after the specified date
5. Remove the `currentTime` constraint
6. Now `IUnleash.IsEnabled("MyFeatureFlag")` returns true

**Expected behavior**
`IUnleash.IsEnabled("MyFeatureFlag")` should return true if the current date is after the specified date

**Screenshots**
![image](https://github.com/user-attachments/assets/bc1a8375-6f60-4f42-bc0c-34b4776cbbeb)

**Desktop (please complete the following information):**
 - OS: Ubuntu (deployed application), Windows (for local development)
 - Browser: irrelevant (server application)
 - Version: 4.1.13

**Comment by tlevesque-ueat** [comment]
I think the problem is here:
https://github.com/Unleash/unleash-client-dotnet/blob/43caba883761bd44ff461f8414a8aa7969cdd3be/src/Unleash/Strategies/Constraints/DateConstraintOperator.cs#L26-L28

If `context.CurrentTime` is not set, it should use the current time. That's what the [documentation](https://docs.getunleash.io/reference/unleash-context) says anyway:
![image](https://github.com/user-attachments/assets/8b4b68e5-7f33-48c1-bd12-a0e48a4af88b)

**Comment by tlevesque-ueat** [comment]
In fact, shouldn't it use `context.CurrentTime` only if `context.ContextName` is `"currentTime"`?
It seems a little strange that it would fall back to `context.CurrentTime` if I specified `"myCustomDate"` as the context name...

**Comment by tlevesque-ueat** [comment]
I submitted a PR
https://github.com/Unleash/unleash-client-dotnet/pull/246

**Comment by daveleek** [comment]
thank you for raising this and for providing a clear bug report + a PR @tlevesque-ueat! We'll have a look and get back to you!
