### ISSUE TITLE
DI scoping issue when not using statics

### ISSUE THREAD

**Issue by scottt732** [Unleash/unleash-client-dotnet#25]
I'm having trouble hooking Unleash up in `IServiceCollection`.  We're trying to use the DI `IDisposable BeginScope()` to store an `IUnleashContextProvider` backed by a `Dictionary<string, string>` as opposed to relying on `HttpContext.Current.Items` as in the README.  The reason is b/c we use the scope pattern outside of ASP.NET Core and would like to be able to use the same Unleash boilerplate code regardless of whether we're in an ASP.NET Core app, a generic host builder, or a simple console app (creating a scope per ASP.NET request, MQ message received, timer interval, etc.).

This almost works, except that the `IUnleashContextProvider` is a property on the `UnleashSettings` class.  `IUnleash` is registered as a singleton (per the docs), `IUnleashContextProvider` is registered as Scoped (also recommended in the docs and critical to capture request/message/etc-specific scope).  `UnleashSettings` is registered as a singleton.

When `ASPNETCORE_ENVIRONMENT=development`, `IServiceCollection.BuildServiceProvider(true)` is called by the framework, which ensures that we're not capturing scoped/transient dependencies in a singleton.  As far as I can tell it's unavoidable given the current architecture... I tried (see here: https://github.com/scottt732/UnleashClientTests/tree/master/UnleashClientTests).

DefaultUnleash(singleton) -> UnleashSettings(singleton) -> UnleashContextProvider(necessarily scoped, effectively captured) = invalid (single state would be shared across requests/race conditions).

The example code in the README ~gets around this issue by effectively having the `UnleashContextProvider` as a singleton which refers to `HttpContext.Current?.Items`.  It will happen to be there in an ASP.NET request because your `BeginRequest` handler puts it there, but this requires using a static for state and breaks the ability for the same configuration to work in different application types.

I think a solution to this would be to decouple DefaultUnleash into 2 pieces--the thing that sets up services & manages the timers and the thing that answers `IsEnabled` questions.  This would remove the `IUnleashContextProvider` from the `UnleashSettings` class.

```
// Configuration
services.AddSingleton<IStrategy, SomeStrategy>();
services.AddSingleton<UnleashSettings>(new UnleashSettings { ... });

// depends on settings & strategies, disposed at app end
services.AddSingleton<IUnleashServiceManager, UnleashServiceManager>(); 

// Request-specific
services.AddScoped<IUnleashContextProvider, DefaultUnleashContextProvider>();
services.AddScoped<IUnleash, DefaultUnleash>();
```

This would allow the `IsEnabled` calls to refer to the scoped `IUnleashContextProvider`

**Comment by silviogreuel** [comment]
This decoupling completely makes sense, maybe a third piece, responsible to store the cached features (currently storing as a .json for now)

**Comment by scottt732** [comment]
For sure.  I've been trying to wrap my head around what the implications are of having a .json cache on each node behind a load balancer as opposed to something like Redis.  Any thoughts there?  I haven't looked at what the other clients are doing.

Should I open another issue to track that?  I had one other about synchronously blocking on the first HTTP round-trip (so our app doesn't service any requests based on a stale cache/default values).

Also are you open to accepting pull requests for any of this?  I'm happy to get my hands dirty.

**Comment by silviogreuel** [comment]
@scottt732 issue https://github.com/Unleash/unleash-client-core/issues/37 created only about decoupling strategies
