### ISSUE TITLE
Consider using HttpClientFactory

### ISSUE THREAD

**Issue by scottt732** [Unleash/unleash-client-dotnet#26]
If you took a dependency on Netstandard2.0 (drop support for .NET Framework <= 4.7.1 I think), you could use the official `HttpClientFactory`, allowing your library/end-users to handle DNS changes gracefully, pool TCP connections, and to configure retry policies.

- https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests
- https://www.nuget.org/packages/Microsoft.Extensions.Http/2.1.0

**Comment by silviogreuel** [comment]
For now, all changes that have a possibility to break the current compatibility will be revisited at the end of milestone https://github.com/Unleash/unleash-client-core/milestone/1

Keep in Touch
