### ISSUE TITLE
Unmanaged memory leak in v5+

### ISSUE THREAD

**Issue by eddietibber** [Unleash/unleash-client-dotnet#264]
**Describe the bug**
Version 5.0.0 and 5.0.1 of the unleash dotnet client leaks unmanaged memory when calling `IUnleash.IsEnabled`. Cannot reproduce on v4.1.15

**To Reproduce**
This code will reproduce it, referencing `Unleash.Client` v 5.0.0:
```csharp
using Unleash;
using Unleash.ClientFactory;

var unleash = new UnleashClientFactory().CreateClient(new UnleashSettings()
{
    UnleashApi = new Uri("..."),
    CustomHttpHeaders = new Dictionary<string, string> { ["Authorization"] = "..." },
}, true);

for (int i = 0; i < 100_000_000; i++)
{
    unleash.IsEnabled("my-feature");
}
```

**Expected behavior**
Very low unmanaged memory consumption

**Screenshots**
Over 600MB unmanaged memory allocated after just 15s
![swappy-20241128_134723](https://github.com/user-attachments/assets/7f256da5-d75c-4a89-b9a9-f6bfa6ca9b8d)

**Desktop:**
- OS: Manjaro linux

**Server:**
 - OS: Docker, using aspnet9.0-alpine image (tested with aspnet9.0 and aspnet9.0-chisel too, same result)

**Additional context:**
This is the memory profile using v 4.1.15
![swappy-20241128_135401](https://github.com/user-attachments/assets/49ee945b-9937-40f7-9588-75250e7b74e6)

**Comment by daveleek** [comment]
Interesting, thank you @eddietibber! We'll take a look and report back!

**Comment by eddietibber** [comment]
Swift response, thank you!

**Comment by sighphyre** [comment]
Okay, 5.0.2 is out, which I believe closes this. Memory seems to be stable now running that same test. Thank you so much for reporting this @eddietibber!
