### ISSUE TITLE
Consider replacing LibLog with Microsoft.Extensions.Logging.Abstractions

### ISSUE THREAD

**Issue by scottt732** [Unleash/unleash-client-dotnet#27]
Consider replacing the LibLog dependency with Microsoft's logging abstractions.  This would allow library consumers to plug this client in to their application and have the library inherit the application-configured logging providers.  

This would require dropping framework support < netstandard2.0 but it's still adaptable in a framework-era ASP.NET code.

**Comment by silviogreuel** [comment]
For now, all changes that have a possibility to break the current compatibility will be revisited at the end of milestone https://github.com/Unleash/unleash-client-core/milestone/1

Keep in Touch

**Comment by thompson-tomo** [comment]
Request should still be considered.
