### ISSUE TITLE
Reload WebApp Project from sample folder

### ISSUE THREAD

**Issue by silviogreuel** [Unleash/unleash-client-dotnet#30]
Reload and make the sample project compile again

**Comment by flerka** [comment]
Hi @silviogreuel ! Is it still relevant? Can't reproduce this issue on master branch. WebApp sample project compiles without errors.

**Comment by silviogreuel** [comment]
Yep, just reload and check for missing folders/imports, and check for AppVeyor build `.\build.ps1 -Target "AppVeyor"`
