### ISSUE TITLE
Decouple estrategies from unleash client leveraging DI

### ISSUE THREAD

**Issue by silviogreuel** [Unleash/unleash-client-dotnet#37]
Decouple strategies from unleash client creation levaraging dependency injection.
A light a discussion on issue from https://github.com/Unleash/unleash-client-core/issues/25 could give some insights

**Comment by silviogreuel** [comment]
Like something https://github.com/App-vNext/Polly#policyregistry maybe

**Comment by silviogreuel** [comment]
Constructor overloading could be, for now, a good idea to handle backward compatibility

**Comment by scottt732** [comment]
I don't think you're going to be able to handle #25 without having at least 1 breaking client change on the `DefaultUnleash` constructor.  `UnleashSettings` currently contains settings + services (including a context provider).  The `IUnleashServices` (with the exception of the `IUnleashContextProvider`) should be a disposable singleton (to stop timers & hopefully avoid ObjectDisposedExceptions at shutdown), the context provider should be request scoped, and the settings (minus services) can be scoped however.  See https://github.com/scottt732/unleash-client-core/blob/master/src/Unleash/DefaultUnleash.cs#L27 vs. https://github.com/Unleash/unleash-client-core/blob/master/src/Unleash/DefaultUnleash.cs#L37

**Comment by silviogreuel** [comment]
To keep going, create a new project, focusing only with .net-core compatibility, and minding out the idea of compatibility until an first release (of the new project), could keep things going, that seems reasonable @scottt732? 

This should allow a more fluid developing...
