### ISSUE TITLE
Client doesn't find features / can't connect to API if `UnleashAPI` doesn't end with `/`

### ISSUE THREAD

**Issue by thomasheartman** [Unleash/unleash-client-dotnet#58]
**Describe the bug**
When provided with a `settings.UnleashApi` value without a trailing slash, the client seems unable to connect to the API.

**To Reproduce**
1. Create a Web API and set up a singleton Unleash service. Use a URL to an Unleash API without the trailing `/`, i.e. `https://<unleash>/api`
2. Check whether a feature that is enabled in the Unleash API is enabled (or can be found).
3. See that the feature can't be found.

**Expected behavior**
The client should be able to connect to the Unleash API regardless of whether the provided API url ends with a `/` or not. 

**Desktop (please complete the following information):**
 - OS: Linux (Docker image: mcr.microsoft.com/dotnet/core/sdk:3.1)

**Additional context**
I ran into this when trying to troubleshoot why the Unleash client told me that none of the toggles were enabled. Double-checking against a version I had running locally revealed that the local version had a trailing slash while the other did not. 

This seems like something that is super easy to miss and could make you scratch your head for hours. I also did not see an explicit mention of this in the readme.

Apart from that, though, the client has been very easy to use and well documented, so good job and thanks!

**Comment by ivarconr** [comment]
I totally agree, and I am sorry that you wasted valuable time on this. We should try to get in a fix for this asap. 

-Thanks for reporting!

**Comment by gnab** [comment]
The fix has been included in the newly released patch version 1.4.1 which should be available from NuGet shortly.

**Comment by thomasheartman** [comment]
That's great! Thanks for being so responsive!
