### ISSUE TITLE
Timing bug in SystemTimerScheduledTaskManager

### ISSUE THREAD

**Issue by einarwh** [Unleash/unleash-client-dotnet#63]
There is a timing bug in SystemTimerScheduledTaskManager that can prevent the Unleash client from properly scheduling the fetch-feature-toggle-task. This means that the Unleash client will silently not fetch feature toggles.

The problem is the gap in time between when a background task's Timer is created and the Timer is registered in the timers dictionary. 

Specifically: the problem occurs if the callback associated with a task's Timer executes and reaches this line before the Timer is put in the dictionary:
https://github.com/Unleash/unleash-client-dotnet/blob/master/src/Unleash/Scheduling/SystemTimerScheduledTaskManager.cs#L33

Then the callback terminates early, and does not go on to reschedule itself by changing the dueTime for the Timer. Since the period for the Timer is set to infinite, it means that the Timer will never fire again. In other words, the callback executes once and terminates early, without running the task, and without making sure that the Timer will fire again.

**Comment by ivarconr** [comment]
Thanks for reporting @einarwh! I feel the whole `Callback` method could benefit a rewrite. 

What do you think about changing the [lines 85-91](https://github.com/Unleash/unleash-client-dotnet/blob/master/src/Unleash/Scheduling/SystemTimerScheduledTaskManager.cs#L85-L91) with the following:

```c#
var timer = new Timer(
    callback: Callback,
    state: callbackState,
    dueTime: Timeout.Infinite,
    period: Timeout.Infinite);

timers.Add(name, timer);
timer.SafeTimerChange(dueTime, Timeout.InfiniteTimeSpan, ref disposeEnded);
```

This will not start the timer before we have successfully added it to the timers dictionary.

**Comment by einarwh** [comment]
That looks like something that would fix the bug, so I would be happy with that change. But the entire process seems needlessly complicated to me, with the caveat that there might be subtle things that I'm unaware of. In particular I don't understand why the Timer needs to be modified on each callback.

**Comment by ivarconr** [comment]
> But the entire process seems needlessly complicated to me

I totally agree. I will try to think of a simple solution. 

I think the main reason to change the intervals is related to the use case of executing the task immediately on initialisation. I think that can be solved simpler.

**Comment by einarwh** [comment]
Right, but in my understanding dueTime is for the delay before firing the first time, and period is for the interval between firings. Why isn't that enough?

**Comment by ivarconr** [comment]
Hmz, good point. I will need to read up on the specifications of the Timer object. Sounds like you are on to something.
