### ISSUE TITLE
Add Type to feature toggle object and expose the feature toggle collection readonly publicly.

### ISSUE THREAD

**Issue by brcpar** [Unleash/unleash-client-dotnet#66]
**Is your feature request related to a problem? Please describe.**
Feature parity with other client. Similar to how the node client allows you to get all feature flag definitions: https://github.com/Unleash/unleash-client-node#3-use-unleash 
Also, the endpoint to grab features from the server "client/features" includes the "Type" field which could be useful if we have access to the entire collection.

**Describe the solution you'd like**
Add "Type" as a string to the FeatureFlag class.
Expose a public getter that returns whatever the most recent collection of feature flag definitions exist.  This could be as simple as adding this to DefaultUnleash.cs
`public ICollection<FeatureToggle> FeatureToggles { get { return services.ToggleCollection.Instance.Features; } }`
Doing this would require adjusting the access modifier on some classes like FeatureToggle or would require some sort of mapping to a new public friendly entity.

**Describe alternatives you've considered**
The only other means of doing this would be to hit the api endpoint manually or directly hitting the database. Neither of these are great options.

**Additional context**
Currently, using the net client, a consumer can only grab a flag by name.  Simply exposing the feature flag definition collection would allow a consumer to grab toggles on a type.

**Comment by ivarconr** [comment]
Ho @brcpar!

Yes, it makes sense to expose the toggle definitions outside of the SDK. 

Up for a PR?

**Comment by brcpar** [comment]
@ivarconr, Added a PR for you to take a look at.  I addressed both exposing the currently loaded feature toggle collection publicly for external consumers and I added the Type property to FeatureToggle class since it was a missing field that comes across the unleash client api.
