### ISSUE TITLE
File not being re-created when deleted.

### ISSUE THREAD

**Issue by mnreggi** [Unleash/unleash-client-dotnet#73]
**Describe the bug**
When the .json file or/and the etag file are removed, the SDK is not re-creating the file.

**To Reproduce**
1. Connect to Unleash.
2. Create UnleashClient.
3. Request Feature Flags.
4. Files are going to be created (.json and etag).
5. Remove both files.
6. The scheduler that has `FetchFeatureToggleTask.cs` will not re-create the file.
7. This is because the logic under `ExecuteAsync` will verify first if the Feature Flags have changed. Because they didn't we are exiting the scheduler.
8. The same scenario happen when the Etag is the same, will exit before checking if the file exists.

**Expected behavior**
The TEMP folder that you suggest, in most of the cases, will be deleted for any reason on the server-side. I would assume that the first thing that we want to check is if the file exists.
If the doesn't exist, we should be aiming to recreate with the FF that where fetched.
Otherwise, we do the same check of `HasChanged` and `Etag = Etag`.

**Screenshots**
![Unleash – FetchFeatureTogglesTask cs](https://user-images.githubusercontent.com/11684897/112537234-4fd7d600-8e13-11eb-9da6-ae7604ce772b.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 87.0
 - We are doing this on the server-side, but I also tested with the samples from cloning the repo.

**Comment by ivarconr** [comment]
Thanks for reporting! 

> If the doesn't exist, we should be aiming to recreate with the FF that where fetched.

Agree, it would be desirable to (re)create the file if it does not exist.
