### ISSUE TITLE
Make GetVariant(string toggleName, UnleashContext context, Variant defaultValue)  public

### ISSUE THREAD

**Issue by dorlandode** [Unleash/unleash-client-dotnet#74]
**Is your feature request related to a problem? Please describe.**
I can pass in a UnleashContext into the IsEnabled method, but not the GetVariant.  As I looked in the source code, I was able to find that there is a private method that does exactly what I want.

**Describe the solution you'd like**
Ideally, the method below would be public and exposed in the interface:
```
public Variant GetVariant(string toggleName, UnleashContext context, Variant defaultValue)
{
      var toggle = GetToggle(toggleName);
      var enabled = CheckIsEnabled(toggleName, context, false);
      var variant = enabled ? VariantUtils.SelectVariant(toggle, context, defaultValue) : defaultValue;

      RegisterVariant(toggleName, variant);
      return variant;
}
```

**Describe alternatives you've considered**
I have looked at adding extension methods, but that gets messy.

**Comment by ivarconr** [comment]
I agree, I see no reasons why it can't be public. I guess most people are using a context-provider. 

PR welcomed!

**Comment by dorlandode** [comment]
How shall I submit the pull request.  I would assume I need to be added as a contributor so I can create a branch?

**Comment by ivarconr** [comment]
> How shall I submit the pull request

Ahh sorry, I take this process for granted; the normal procedure is to fork the repo and submit an upstream PR from your fork.

**Comment by dorlandode** [comment]
Ok, thanks

**Comment by nhathongly** [comment]
Any update? :(
