### ISSUE TITLE
Allow configurable retry strategies for fetching feature toggles

### ISSUE THREAD

**Issue by SondreJAttensi** [Unleash/unleash-client-dotnet#97]
**Is your feature request related to a problem? Please describe.**
I'd like a way to set a retry strategy for fetching feature toggles. Currently if the Unleash server is unreachable, or if there is some wrong configuration, the fetch feature toggle task will throw errors every 30 seconds (by default).

**Describe the solution you'd like**
A way to configure a retry strategy for fetching feature toggles, or being able to pause and start the task. Example of strategies: "If fetching toggles fails five times in a row, pause for one hour" or "If fetching feature toggles fail, wait with exponential or incremental backoff up to 30 minutes until succeeding"

**Describe alternatives you've considered**
One alternative has been to use synchronous startup, however I don't want the application to fail to launch if something is wrong with unleash at the moment, just to behave as if the client returned the default value every time I call `IsEnabled()`.

Another alternative is to create my own implementation of `IUnleash` or skip using the SDK, however this feels like recreating the wheel when the other features Ineed are already implemented.

The alternative I currently use is to ping the server during startup before registering the `DefaultUnleash` for dependency injection. If I get a 200 OK I continue as normal, but if I don't get a response I set the intervals for fetching toggles and sending metrics to `TimeSpan.Zero`. This allows me to use the `IUnleash` as normal in the implementations, but the only way to resume fetching toggles is to restart the service.

**Additional context**
I know this is a bit of a edge case, as once the Unleash environment is properly configured for all environments this most likely won't be a frequent scenario, but during the implementation phase I'd like to push early implementations without everything being ready just yet.

**Comment by sighphyre** [comment]
Hi @SondreJAttensi thanks so much for raising this. I think I need to ask a few questions before I dig into this. From your description it sounds like the core problem is that the .NET SDK is being noisy in the logs? Is that the correct understanding, or are you having to wrap code in try/catch to avoid a crash here? My second question, is that I'm not quite sure how the synchronous startup deals with the problem you've described in the first case? It sounds like you may have encountered a bug of some shape here?

We are a bit hesitant to add options for a more complex fetching strategy, mostly because when Unleash is working fine, you shouldn't need it (that's not a no, just that we need a strong usecase in order to prioritise this)

**Comment by SondreJAttensi** [comment]
> Hi @SondreJAttensi thanks so much for raising this. I think I need to ask a few questions before I dig into this. From your description it sounds like the core problem is that the .NET SDK is being noisy in the logs? Is that the correct understanding, or are you having to wrap code in try/catch to avoid a crash here? My second question, is that I'm not quite sure how the synchronous startup deals with the problem you've described in the first case? It sounds like you may have encountered a bug of some shape here?
> 
> We are a bit hesitant to add options for a more complex fetching strategy, mostly because when Unleash is working fine, you shouldn't need it (that's not a no, just that we need a strong usecase in order to prioritise this)

Hi! Yes, the .NET SDK is being noisy in logs, as by default it would try to fetch the feature toggles every 30 seconds. This happens in the background task that the SDK starts, in one of the environments where I hadn't set up the Unleash server yet, so there was no connection to make.

You are correct that synchronous startup wouldn't exactly solve the problem, as that would prevent the service from starting. I might have phrased myself poorly. What I meant is just that it's one of the alternatives I looked into to prevent the background task to be ran every 30 seconds and therefore stop noisy logs, but it's not really a viable alternative as I'd like the service to run normally even if Unleash isn't responding.

And I completely understand if this is a bit of an edge case scenario! I also expect that once my team has Unleash set up and working fine in all our environments this will not be a prevalent issue at all, but I figured it'd be worth asking!

**Comment by sighphyre** [comment]
Ah! Thanks for the info that makes sense! I don't think this is a thing that's going to make its way onto our priority list for fairly long while to be honest. We do accept pull requests though, so if you really want it and you can think of a way to do it without changing the API then I would be very open to taking a look!

**Comment by sighphyre** [comment]
Going to close this for now since we're not going to tackle this directly. This can be reopened if needs be!
